training:
  min_datasize_thres: 600000
  overlap_buff: 1500
  feature_size: -1
  max_hp_evals: 50
  name: "LGBM"
  learning_rate: 0.001
  bagging_fraction: 0.8
  feature_fraction: 0.8
  hyperparameters:
    num_leaves:
      type: randint
      min: 50
      max: 200
